'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Code2, ExternalLink, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { apiFetch } from '@/lib/adminApi';

type Project = { _id:string; title:string; shortDescription:string; technologies:string[]; liveUrl?:string; githubUrl?:string; published:boolean; featured:boolean };
export default function ProjectsPage(){
 const [items,setItems]=useState<Project[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{try{setLoading(true);setError('');const r=await apiFetch('/projects');setItems(r.data||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const remove=async(id:string)=>{if(!window.confirm('Delete this project?'))return;try{await apiFetch(`/projects/${id}`,{method:'DELETE'});setItems(x=>x.filter(p=>p._id!==id))}catch(e:any){setError(e.message)}};
 const filtered=items.filter(p=>p.title.toLowerCase().includes(q.toLowerCase()));
 return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-extrabold text-white">All Projects</h2><p className="mt-1 text-sm text-white/35">Manage the projects shown on your portfolio.</p></div><Link href="/admin/projects/new" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#f5a623] px-4 py-3 text-xs font-extrabold text-black"><Plus size={16}/> Add Project</Link></div><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.02] px-4 py-3"><Search size={17} className="text-white/25"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/20"/></div>{error&&<p className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-xs text-red-300">{error}</p>}<div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]"><div className="hidden grid-cols-[1.5fr_1fr_.7fr_.55fr] gap-4 border-b border-white/10 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-white/25 md:grid"><span>Project</span><span>Technologies</span><span>Status</span><span className="text-right">Actions</span></div>{loading?<div className="p-8 text-center text-sm text-white/35">Loading projects...</div>:filtered.length===0?<div className="p-8 text-center text-sm text-white/35">No projects found.</div>:filtered.map(p=><div key={p._id} className="grid gap-4 border-b border-white/8 px-5 py-5 last:border-0 md:grid-cols-[1.5fr_1fr_.7fr_.55fr] md:items-center"><div><div className="flex items-center gap-2"><p className="text-sm font-bold text-white">{p.title}</p>{p.featured&&<span className="rounded-full bg-[#f5a623]/10 px-2 py-0.5 text-[9px] font-bold text-[#f5a623]">Featured</span>}</div><p className="mt-1 text-xs leading-5 text-white/35">{p.shortDescription}</p></div><div className="flex flex-wrap gap-1.5">{(p.technologies||[]).map(t=><span key={t} className="rounded-full border border-white/10 bg-white/[0.03] px-2 py-1 text-[9px] text-white/45">{t}</span>)}</div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-semibold ${p.published?'bg-emerald-400/10 text-emerald-300':'bg-white/5 text-white/40'}`}>{p.published?'Published':'Draft'}</span><div className="flex items-center justify-start gap-1 md:justify-end"><Link href={`/admin/projects/${p._id}/edit`} className="rounded-lg p-2 text-white/30 hover:text-[#f5a623]"><Pencil size={15}/></Link>{p.liveUrl&&<a href={p.liveUrl} target="_blank" className="rounded-lg p-2 text-white/30 hover:text-[#f5a623]"><ExternalLink size={15}/></a>}{p.githubUrl&&<a href={p.githubUrl} target="_blank" className="rounded-lg p-2 text-white/30 hover:text-[#f5a623]"><Code2 size={15}/></a>}<button onClick={()=>remove(p._id)} className="rounded-lg p-2 text-white/30 hover:text-red-300"><Trash2 size={15}/></button></div></div>)}</div></div>
}
