'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Save } from 'lucide-react';
import { apiFetch } from '@/lib/adminApi';

type Form={title:string;shortDescription:string;description:string;technologies:string;liveUrl:string;githubUrl:string;featured:boolean;published:boolean;displayOrder:number};
const empty:Form={title:'',shortDescription:'',description:'',technologies:'',liveUrl:'',githubUrl:'',featured:false,published:true,displayOrder:0};
export default function ProjectForm({mode,projectId}:{mode:'new'|'edit';projectId?:string}){const [form,setForm]=useState(empty);const [loading,setLoading]=useState(mode==='edit');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(mode==='edit'&&projectId)apiFetch(`/projects/${projectId}`).then(r=>{const p=r.data;setForm({title:p.title||'',shortDescription:p.shortDescription||'',description:p.description||'',technologies:(p.technologies||[]).join(', '),liveUrl:p.liveUrl||'',githubUrl:p.githubUrl||'',featured:!!p.featured,published:p.published!==false,displayOrder:p.displayOrder||0})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[mode,projectId]);
 const set=(k:keyof Form,v:any)=>setForm(f=>({...f,[k]:v}));
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{setSaving(true);setError('');const payload={...form,technologies:form.technologies.split(',').map(x=>x.trim()).filter(Boolean)};const r=mode==='new'?await apiFetch('/projects',{method:'POST',body:JSON.stringify(payload)}):await apiFetch(`/projects/${projectId}`,{method:'PUT',body:JSON.stringify(payload)});if(r.success)window.location.href='/admin/projects'}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 if(loading)return <div className="p-8 text-sm text-white/40">Loading project...</div>;
 return <form onSubmit={save} className="mx-auto max-w-5xl space-y-6"><div className="flex items-center gap-3"><Link href="/admin/projects" className="rounded-xl border border-white/10 bg-white/[0.02] p-2.5 text-white/50"><ArrowLeft size={18}/></Link><div><h2 className="text-2xl font-extrabold text-white">{mode==='new'?'Add Project':'Edit Project'}</h2><p className="mt-1 text-sm text-white/35">Changes are saved directly to the backend.</p></div></div>{error&&<p className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-xs text-red-300">{error}</p>}<section className="space-y-5 rounded-2xl border border-white/10 bg-white/[0.02] p-5 sm:p-7"><Field label="Project title" value={form.title} onChange={v=>set('title',v)} required/><Field label="Short description" value={form.shortDescription} onChange={v=>set('shortDescription',v)} required/><label><span className="mb-2 block text-xs font-semibold text-white/60">Full description</span><textarea required value={form.description} onChange={e=>set('description',e.target.value)} rows={7} className="w-full resize-none rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none focus:border-[#f5a623]/50"/></label><Field label="Technologies (comma separated)" value={form.technologies} onChange={v=>set('technologies',v)}/><div className="grid gap-5 sm:grid-cols-2"><Field label="Live URL" value={form.liveUrl} onChange={v=>set('liveUrl',v)}/><Field label="GitHub URL" value={form.githubUrl} onChange={v=>set('githubUrl',v)}/></div><div className="grid gap-4 sm:grid-cols-3"><label className="flex items-center justify-between rounded-xl border border-white/8 bg-black/20 p-3 text-xs text-white/55">Published<input type="checkbox" checked={form.published} onChange={e=>set('published',e.target.checked)} className="accent-[#f5a623]"/></label><label className="flex items-center justify-between rounded-xl border border-white/8 bg-black/20 p-3 text-xs text-white/55">Featured<input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)} className="accent-[#f5a623]"/></label><label><span className="mb-2 block text-[10px] font-semibold text-white/45">Display order</span><input type="number" value={form.displayOrder} onChange={e=>set('displayOrder',Number(e.target.value)||0)} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-xs text-white outline-none"/></label></div></section><div className="flex justify-end gap-3 border-t border-white/10 pt-5"><Link href="/admin/projects" className="rounded-xl border border-white/10 px-5 py-3 text-xs font-semibold text-white/55">Cancel</Link><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#f5a623] px-5 py-3 text-xs font-extrabold text-black disabled:opacity-50"><Save size={15}/>{saving?'Saving...':'Save Project'}</button></div></form>}
function Field({label,value,onChange,required=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="block"><span className="mb-2 block text-xs font-semibold text-white/60">{label}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none placeholder:text-white/20 focus:border-[#f5a623]/50"/></label>}
